version: "3"
services:
  web_service:
    container_name: php_web
    image: php:7.2.2-apache
    volumes:
     - /var/www/html:/var/www/html
    ports:
     - 8089:80
  db_service:
    container_name: mysql_web
    image: mariadb:latest
    volumes:
     - /var/lib/mysql:/var/lib/mysql
    ports:
     - 3306:3306
    environment:
       MYSQL_ROOT_PASSWORD: root_pass
       MYSQL_DATABASE: database_web
       MYSQL_USER: devuser
       MYSQL_PASSWORD: devpass
